from __future__ import annotations

import base64
import copy
import json
import shutil
from pathlib import Path

import pytest
import yaml

from cuif_eval.pptx.extract import summarize_pptx

ROOT = Path(__file__).resolve().parents[1]
TOY_TASK = ROOT / "poc" / "tasks" / "toy_pptx_layout"
PNG_1X1 = base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=")


@pytest.fixture
def toy_task() -> Path:
    return TOY_TASK


@pytest.fixture
def copied_task(tmp_path: Path) -> Path:
    dst = tmp_path / "toy_pptx_layout"
    shutil.copytree(TOY_TASK, dst)
    return dst


def load_manifest_dict(task: Path) -> dict:
    return yaml.safe_load((task / "manifest.yaml").read_text(encoding="utf-8"))


def write_manifest_dict(task: Path, data: dict) -> Path:
    path = task / "manifest.yaml"
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return path


@pytest.fixture
def mutate_manifest(copied_task: Path):
    def _mutate(fn):
        data = load_manifest_dict(copied_task)
        data = copy.deepcopy(data)
        fn(data)
        write_manifest_dict(copied_task, data)
        return copied_task / "manifest.yaml"

    return _mutate


@pytest.fixture(autouse=True)
def fast_preview_rendering(monkeypatch, request):
    if Path(str(request.path)).name == "test_rendering.py":
        return

    def fake_render_pptx_previews(pptx_path: str | Path, previews_dir: str | Path, label: str) -> dict:
        previews_dir = Path(previews_dir)
        safe_label = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in label)
        target_dir = previews_dir / safe_label
        target_dir.mkdir(parents=True, exist_ok=True)
        summary = summarize_pptx(Path(pptx_path))
        summary_path = target_dir / "summary.json"
        summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        html_path = target_dir / "summary.html"
        html_path.write_text("<!doctype html><meta charset='utf-8'><p>fake preview</p>", encoding="utf-8")
        images = []
        for slide in range(1, int(summary.get("slide_count", 1)) + 1):
            image = target_dir / f"slide-{slide}.png"
            image.write_bytes(PNG_1X1)
            images.append(image.as_posix())
        return {
            "status": "rendered",
            "renderer": "pytest-fake",
            "summary": summary_path.as_posix(),
            "html": html_path.as_posix(),
            "images": images,
            "message": "Fake preview generated by tests.",
        }

    monkeypatch.setattr("cuif_eval.reports.render_pptx_previews", fake_render_pptx_previews)
    monkeypatch.setattr("cuif_eval.checks.pptx.render_pptx_previews", fake_render_pptx_previews)
    monkeypatch.setattr("cuif_eval.checks.judge.render_pptx_previews", fake_render_pptx_previews)
